version: "3"
services:
  golang:
    image: "nextdenv/golang-1.15.0:latest"
    ports: 
    # export containers ssh port, for vscode connection
    - "20580:22"
    volumes: 
    # volume host code directory to container, keep from losing code when container recreated.
    - "/home/code/node:/code"
    # volume ssh login info, create a ssh directory for each user,
    # including authorized_keys for vscode connection and id_rsa for git clone.
    - "/root/users/narro:/root/.ssh"