version: "3"
services:
  node:
    image: "nextdenv/node-14.8.0:latest"
    ports: 
    # export containers ssh port, for vscode connection
    - "8080:8080"
    volumes: 
    # volume host code directory to container, keep from losing code when container recreated.
    - "/home/code/node:/home/coder"
